version: '3.8'

services:
  frontend:
    build: .
    image: manhcuongdtbk/bachkhoadienmay-frontend
    stdin_open: true
    tty: true
    ports:
      - 8080:8080
    volumes:
      - .:/frontend
      - node_modules:/frontend/node_modules
    networks:
      - bachkhoadienmay-network

volumes:
  node_modules:

networks:
  bachkhoadienmay-network:
    name: bachkhoadienmay-network
